spring:
  application:
    name: FlightBookingSystem

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flight_booking
    username: manish123
    password: Manish@123
  #    username: apurba
  #    password: apurba



  jpa:
    hibernate:
      property:
        dialect : org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
    show-sql: true